/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario.views;

import inventario.config.Conexion;
import inventario.modelo.Producto;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Inventario extends javax.swing.JFrame {
    DefaultTableModel model;
    ArrayList<Producto> listaProductos;
    int posicion = -1;
    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        String[] titulos = {"ID_PRODUCTO","CODIGO","NOMBRE","CANTIDAD","PRECIO","CATEGORIA"};
        
        model = new DefaultTableModel(null,titulos);
        tblProductos.setModel(model);
        cargarDatos();
//        setSize(width/2,height/2);//para darle tamaño a la vista
        setLocationRelativeTo(null);//para posicionar en este caso centrar
        
        tblProductos.removeColumn(tblProductos.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        pnlAgregarProducto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioUnidad = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCandelarAgregar = new javax.swing.JButton();
        pnlEdidarProducto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarCantidad = new javax.swing.JButton();
        btnRestarCantidad = new javax.swing.JButton();
        btnAsignarCantidad = new javax.swing.JButton();
        txtCantidadAModificar = new javax.swing.JTextField();
        txtPrecioActual = new javax.swing.JTextField();
        btnCancelarModificar = new javax.swing.JButton();
        lblCantidadActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inventario");

        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnProductos.setText("Productos");

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jLabel2.setText("Agregar producto");

        txtIdProducto.setText("0");

        jLabel3.setText("Codigo:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Precio Unidad:");

        jLabel7.setText("Categoria:");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtPrecioUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioUnidadKeyTyped(evt);
            }
        });

        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCandelarAgregar.setText("Cancelar");
        btnCandelarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandelarAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarProductoLayout = new javax.swing.GroupLayout(pnlAgregarProducto);
        pnlAgregarProducto.setLayout(pnlAgregarProductoLayout);
        pnlAgregarProductoLayout.setHorizontalGroup(
            pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(69, 69, 69)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarProductoLayout.createSequentialGroup()
                        .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCandelarAgregar))
                            .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtCategoria))
                                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                                        .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(73, 73, 73)
                                        .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                            .addComponent(txtNombreProducto)))
                                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtPrecioUnidad)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregar)))
                        .addGap(31, 31, 31))))
        );
        pnlAgregarProductoLayout.setVerticalGroup(
            pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAgregarProductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecioUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnCandelarAgregar)
                .addContainerGap())
        );

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Precio Unidad:");

        btnAgregarCantidad.setText("+");
        btnAgregarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCantidadActionPerformed(evt);
            }
        });

        btnRestarCantidad.setText("-");
        btnRestarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarCantidadActionPerformed(evt);
            }
        });

        btnAsignarCantidad.setText("✓");
        btnAsignarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCantidadActionPerformed(evt);
            }
        });

        txtCantidadAModificar.setText("0");

        btnCancelarModificar.setText("Cancelar");
        btnCancelarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarModificarActionPerformed(evt);
            }
        });

        lblCantidadActual.setText("Cantidad actual:");

        javax.swing.GroupLayout pnlEdidarProductoLayout = new javax.swing.GroupLayout(pnlEdidarProducto);
        pnlEdidarProducto.setLayout(pnlEdidarProductoLayout);
        pnlEdidarProductoLayout.setHorizontalGroup(
            pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEdidarProductoLayout.createSequentialGroup()
                .addGroup(pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEdidarProductoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lblCantidadActual)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEdidarProductoLayout.createSequentialGroup()
                                .addComponent(txtCantidadAModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRestarCantidad))
                            .addComponent(txtPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsignarCantidad))
                    .addGroup(pnlEdidarProductoLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnCancelarModificar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEdidarProductoLayout.setVerticalGroup(
            pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEdidarProductoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblCantidadActual)
                .addGap(18, 18, 18)
                .addGroup(pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestarCantidad)
                    .addComponent(btnAgregarCantidad)
                    .addComponent(txtCantidadAModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(pnlEdidarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnAsignarCantidad)
                    .addComponent(txtPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarModificar)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProveedores)
                        .addGap(181, 181, 181)
                        .addComponent(btnProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsuarios)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pnlAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlEdidarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProveedores)
                    .addComponent(btnProductos)
                    .addComponent(btnUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEdidarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        //mostrar la vista de usuario
        FormUsuario vistaUsuario = new FormUsuario();
        vistaUsuario.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        FormProveedor vistaProveedores = new FormProveedor();
        vistaProveedores.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            Conexion objConexion = new Conexion();
            objConexion.conectar();
            Producto objProducto = recuperarDatosGUI();
            System.out.println("" + objProducto.toString());
            ResultSet respuesta = objConexion.consultarRegistro("Select * from producto where codigo = '" + objProducto.getCodigo() + "'");
            if (!respuesta.isBeforeFirst()) {//si retorna false el codigo no esta el la bd
                String sentencia = "INSERT INTO producto (codigo,nombre,cantidad,precio,categoria) VALUES('"+objProducto.getCodigo()+"','"+objProducto.getNombre()+"','"+objProducto.getCantidad()+"','"+objProducto.getPrecio()+"','"+objProducto.getCategoria()+"')";
                System.out.println("la sentencia es " + sentencia);
                objConexion.ejecutarSentenciSQL(sentencia);
            }else{
                JOptionPane.showMessageDialog(null, "codigo ya registrado");
            }
            objConexion.desconectar();
        } catch (Exception ex) {
            System.err.println("Error al guardar " + ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    //metodo para obtener solo numeros
    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') || (caracter > '9')) && (caracter != '.')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    //metodo para obtener solo numeros
    private void txtPrecioUnidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioUnidadKeyTyped
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0') || (caracter > '9')) && (caracter != '.')) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtPrecioUnidadKeyTyped

    //capturamos el click en la columna de la trabla
    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        if(evt.getClickCount() == 1){
            try {
                pnlAgregarProducto.setVisible(false);
                pnlEdidarProducto.setVisible(true);
                JTable receptor = (JTable)evt.getSource();
                lblCantidadActual.setText("Cantidad actual: "+receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
                txtCantidadAModificar.setText("0");
                txtPrecioActual.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
                //en la lista buscamos la posición
                for (int i =0 ; i < listaProductos.size() ; i++) {
                    //para actualizar el objeto
                    if(listaProductos.get(i).getId_producto() == Double.parseDouble(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString())){
                        this.posicion =i;
                    }
                }
            } catch (Exception e) {
                System.err.println("Error en click columna de la tabla "+e);
            }
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnCancelarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarModificarActionPerformed
        pnlAgregarProducto.setVisible(true);
        pnlEdidarProducto.setVisible(false);
    }//GEN-LAST:event_btnCancelarModificarActionPerformed

    private void btnCandelarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandelarAgregarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCandelarAgregarActionPerformed

    //agregar cantidad al producto actual
    private void btnAgregarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCantidadActionPerformed
        double cantidad = this.listaProductos.get(this.posicion).getCantidad();
        double cantidadAgregar = Double.parseDouble(txtCantidadAModificar.getText());
        cantidad = cantidad +cantidadAgregar;
        this.listaProductos.get(this.posicion).setCantidad(cantidad);
        Producto p = this.listaProductos.get(this.posicion);
        String sentencia = "UPDATE producto SET codigo = '"+p.getCodigo()+"',nombre = '"+p.getNombre()+"',cantidad = '"+p.getCantidad()+"',precio= '"+p.getPrecio()+"',categoria = '"+p.getCategoria()+"' where id_producto = '"+p.getId_producto()+"'";
        Conexion c = new Conexion();
        c.ejecutarSentenciSQL(sentencia);
        cargarDatos();
        c.desconectar();
        lblCantidadActual.setText("Cantidad actual: "+cantidad);
        txtCantidadAModificar.setText("0");
    }//GEN-LAST:event_btnAgregarCantidadActionPerformed
    //retirar cantidad
    private void btnRestarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarCantidadActionPerformed
        double cantidad = this.listaProductos.get(this.posicion).getCantidad();
        double cantidadAgregar = Double.parseDouble(txtCantidadAModificar.getText());
        cantidad = cantidad - cantidadAgregar;
        if(cantidad >= 0){
            this.listaProductos.get(this.posicion).setCantidad(cantidad);
            Producto p = this.listaProductos.get(this.posicion);
            String sentencia = "UPDATE producto SET codigo = '"+p.getCodigo()+"',nombre = '"+p.getNombre()+"',cantidad = '"+p.getCantidad()+"',precio= '"+p.getPrecio()+"',categoria = '"+p.getCategoria()+"' where id_producto = '"+p.getId_producto()+"'";
            Conexion c = new Conexion();
            c.ejecutarSentenciSQL(sentencia);
            cargarDatos();
            c.desconectar();
            lblCantidadActual.setText("Cantidad actual: "+cantidad);
            txtCantidadAModificar.setText("0");
        }else{
            JOptionPane.showMessageDialog(null,"Error al retirar la cantidad");
        }
        
    }//GEN-LAST:event_btnRestarCantidadActionPerformed

    //cambia el valor al producto por unidad
    private void btnAsignarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCantidadActionPerformed
        double precio = Double.parseDouble(txtPrecioActual.getText());
        Producto p = this.listaProductos.get(this.posicion);
        p.setPrecio(precio);
        String sentencia = "UPDATE producto SET codigo = '"+p.getCodigo()+"',nombre = '"+p.getNombre()+"',cantidad = '"+p.getCantidad()+"',precio= '"+p.getPrecio()+"',categoria = '"+p.getCategoria()+"' where id_producto = '"+p.getId_producto()+"'";
        Conexion c = new Conexion();
        c.ejecutarSentenciSQL(sentencia);
        cargarDatos();
    }//GEN-LAST:event_btnAsignarCantidadActionPerformed

    public void limpiar(){
        txtCodigoProducto.setText("");
        txtNombreProducto.setText("");
        txtCantidad.setText("");
        txtPrecioUnidad.setText("");
        txtCategoria.setText("");
    }
    
    public void cargarDatos(){
        while(model.getRowCount() > 0){
            model.removeRow(0);//limpia la tabla
        }
        Conexion objConexion = new Conexion();
        this.listaProductos = new ArrayList<>();
        try {
            ResultSet respuesta = objConexion.consultarRegistro("Select * from producto");
            while(respuesta.next()){
                Producto producto = new Producto();
                producto.setId_producto(Long.parseLong(respuesta.getString("id_producto")));
                producto.setCodigo(respuesta.getString("codigo"));
                producto.setNombre(respuesta.getString("nombre"));
                producto.setCantidad(Double.parseDouble(respuesta.getString("cantidad")));
                producto.setPrecio(Double.parseDouble(respuesta.getString("precio")));
                producto.setCategoria(respuesta.getString("categoria"));
                Object [] objProducto = {producto.getId_producto(),producto.getCodigo(),producto.getNombre(),producto.getCantidad(),producto.getPrecio(),producto.getCategoria()};
                listaProductos.add(producto);
                model.addRow(objProducto);
            }
        } catch (Exception e) {
            System.err.println("inventario: error "+e);
        }
        
    }
    
    private Producto recuperarDatosGUI() {
        Producto producto = new Producto();
        if (txtCodigoProducto.getText().isEmpty() || txtNombreProducto.getText().isEmpty() || txtCantidad.getText().isEmpty() || txtPrecioUnidad.getText().isEmpty() || txtCategoria.getText().isEmpty()
                || txtCodigoProducto.getText().isBlank() || txtNombreProducto.getText().isBlank() || txtCantidad.getText().isBlank() || txtPrecioUnidad.getText().isBlank() || txtCategoria.getText().isBlank()) {

            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        } else {
            producto.setId_producto(Long.parseLong(txtIdProducto.getText()));
            producto.setCodigo(txtCodigoProducto.getText());
            producto.setNombre(txtNombreProducto.getText());
            try {
                producto.setCantidad(Double.parseDouble(txtCantidad.getText()));
                producto.setPrecio(Double.parseDouble(txtPrecioUnidad.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en algun valor númerico");
            }
            producto.setCategoria(txtCategoria.getText());
        }
        return producto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarCantidad;
    private javax.swing.JButton btnAsignarCantidad;
    private javax.swing.JButton btnCancelarModificar;
    private javax.swing.JButton btnCandelarAgregar;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnRestarCantidad;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadActual;
    private javax.swing.JPanel pnlAgregarProducto;
    private javax.swing.JPanel pnlEdidarProducto;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadAModificar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioActual;
    private javax.swing.JTextField txtPrecioUnidad;
    // End of variables declaration//GEN-END:variables
}
