/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario.views;

import inventario.modelo.DatosContacto;
import inventario.modelo.Proveedor;
import inventario.tabla.CeldaRenderer;
import inventario.tabla.EncabezadoRenderer;
import inventario.tabla.TablaModelo;
import java.util.ArrayList;
import javax.swing.table.TableColumnModel;

/**
https://www.jc-mouse.net/java/sub-tablas-agregar-tablas-dentro-de-otras-tablas-en-java
 */
public class Tabla extends javax.swing.JFrame {

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        iniciarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarTabla() {
        //Los datos
        TablaModelo model = new TablaModelo();
        //1 libro
//        ArrayList<DatosContacto> datos = new ArrayList<>();
//        datos.add(new DatosContacto(123, "Novela"));        
//        Proveedor proveedor1 = new Proveedor("Charles Dickens", "UK", datos);
        DatosContacto datos = new DatosContacto();
        datos.setTelefono(123);
        datos.setDireccion("dir1");
        Proveedor proveedor1 = new Proveedor();
        proveedor1.setNit("ni1");
        proveedor1.setNombre("UD");
        proveedor1.agregarDatos(datos);
        
        //2 libros
//        ArrayList<DatosContacto> datos2 = new ArrayList<>();
//        datos2.add(new DatosContacto(456, "Novela"));
//        datos2.add(new DatosContacto(654, "Novela"));        
//        Proveedor proveedor2 = new Proveedor("J. R. R. Tolkien", "Sud Africa", datos2);
        
        Proveedor proveedor2 = new Proveedor();
            proveedor2.setNit("ni12");
            proveedor2.setNombre("UD1");
        DatosContacto datos2 = new DatosContacto();
        datos2.setTelefono(456);
        datos2.setDireccion("dir1");
            proveedor2.agregarDatos(datos2);
        datos2 = new DatosContacto();
        datos2.setTelefono(654);
        datos2.setDireccion("ud2");
            proveedor2.agregarDatos(datos2);
        
        
        
        //3 libros
//        ArrayList<DatosContacto> datos3 = new ArrayList<>();
//        datos3.add(new DatosContacto(987, "Novela"));
//        datos3.add(new DatosContacto(987, "Novela"));
//        datos3.add(new DatosContacto(987, "Cuentos"));
//        Proveedor proveedor3 = new Proveedor("Julio Verne", "Francia", datos3);
        Proveedor proveedor3 = new Proveedor();
            proveedor2.setNit("ni12");
            proveedor2.setNombre("UD1");
        datos2 = new DatosContacto();
        datos2.setTelefono(456);
        datos2.setDireccion("dir1");
            proveedor2.agregarDatos(datos2);
        datos2 = new DatosContacto();
        datos2.setTelefono(654);
        datos2.setDireccion("ud2");
            proveedor2.agregarDatos(datos2);
        datos2 = new DatosContacto();
        datos2.setTelefono(654);
        datos2.setDireccion("ud2");
            proveedor2.agregarDatos(datos2);
        //cero libros
        Proveedor proveedor4 = new Proveedor("H. G. Wells", "UK", new ArrayList<>());

        //se agregan al modelo
        model.addProveedor(proveedor1);
        model.addProveedor(proveedor2);
        model.addProveedor(proveedor3);
        model.addProveedor(proveedor4);
        
        //se establece el modelo de datos
        jTable1.setModel(model); 
        //se asignan los render a las celdas y el encabezado
        jTable1.getTableHeader().setDefaultRenderer(new EncabezadoRenderer());        
        
        TableColumnModel tcm = jTable1.getColumnModel();
        for (int it = 0; it < tcm.getColumnCount(); it++) {
            tcm.getColumn(it).setCellRenderer(new CeldaRenderer());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
